### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by tarikkavaz** [jccguimaraes/atom-project-viewer#105]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.40

### Stack Trace

Uncaught TypeError: Cannot read property 'type' of undefined

```
At /Users/tarik/.atom/packages/project-viewer/src/index.js:675

TypeError: Cannot read property 'type' of undefined
    at disposables.add.atom.project.onDidChangePaths (/Users/tarik/.atom/packages/project-viewer/src/index.js:675:39)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:233:27)
    at Project.module.exports.Project.deserialize (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:116:19)
    at Object.projectDeserialization (/Users/tarik/.atom/packages/project-viewer/src/states.js:11:22)
    at pv-list-item.clickListener (/Users/tarik/.atom/packages/project-viewer/src/list-item-component.js:72:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "markdown-preview",
      "terminal-plus"
    ],
    "excludeVcsIgnoredPaths": false,
    "ignoredNames": [
      "*.pyc"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "git-diff"
    ],
    "projectHome": "~/Sites/BilgiRepos/",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ]
  },
  "project-viewer": {
    "panelPosition": "Left"
  }
}
```

### Installed Packages

```coffee
# User
atom-bourbon-snippets, v0.15.0 (inactive)
atom-coda, v0.3.0 (inactive)
atom-material-syntax, v0.4.6 (active)
atom-material-ui, v1.3.8 (inactive)
atom-panic-palette-syntax, v1.0.0 (inactive)
atom-react-preview, v2.0.0 (active)
Atom-Syntax-highlighting-for-Sass, v0.5.0 (active)
atom-wrap-in-tag, v0.6.0 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-sass, v0.1.0 (active)
bootstrap-3-snippetset, v0.0.6 (active)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.3 (active)
dark-bint-syntax, v0.8.9 (inactive)
dark-bint-ui, v0.5.2 (inactive)
dev-lorem, v0.1.2 (inactive)
django-atom, v0.2.4 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.25 (active)
flexbox-snippets, v0.3.0 (active)
fonts, v1.7.0 (active)
kuali-dark-ui, v1.0.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
native-ui, v0.19.1 (inactive)
northem-dark-atom-syntax, v2.0.0 (inactive)
northem-dark-atom-ui, v2.0.0 (inactive)
nucleus-dark-ui, v0.10.19 (inactive)
one-dark-shade-ui, v0.1.0 (inactive)
panic-palette, v0.1.0 (inactive)
paste-table, v0.1.0 (inactive)
pigments, v0.37.0 (active)
pinned-tabs, v0.4.1 (active)
project-viewer, v0.3.40 (active)
react, v0.16.1 (active)
sepia-syntax, v1.0.8 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (inactive)
slime, v1.6.1 (inactive)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.8.0 (active)
terminal-plus, v0.14.5 (inactive)
text-manipulation, v0.6.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
@tarikkavaz, please check with `0.3.41` update.

Sorry for this

**Comment by tarikkavaz** [comment]
👍
