### ISSUE TITLE
Uncaught TypeError: Cannot read property 'visible' of null

### ISSUE THREAD

**Issue by zhudock** [jccguimaraes/atom-project-viewer#118]
# ISSUE
Uncaught TypeError: Cannot read property 'visible' of null.

## Steps
With Project Viewer panel closed, attempt to open the panel

## Environment
**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'visible' of null

```
At C:\Users\zrh535\.atom\packages\project-viewer\src\main.js:350

TypeError: Cannot read property 'visible' of null
    at undefined._togglePanel (/packages/project-viewer/src/main.js:350:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1158:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:57.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:32.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:25.8.0 project-viewer:togglePanel (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.12.1 
atom-beautify 0.29.17 
autocomplete-oracle 0.4.0 
busy 0.7.0 
console-panel 0.2.1 
file-icons 2.0.15 
git-plus 7.2.2 
language-batch 0.4.0 
language-dots 0.0.4 
language-oracle 1.6.2 
language-sqr 0.8.0 
language-vbscript 0.7.0 
line-ending-converter 1.3.2 
linter 1.11.22 
minimap 4.26.8 
pigments 0.39.0 
project-view 0.6.1 
project-viewer 1.0.3 
save-session 0.15.7 
svn 0.0.13 
symbols-tree-view 0.13.2 
synced-sidebar 0.4.3 
tabasco 0.5.0 
tabs-to-spaces 1.0.3 
tortoise-svn 0.5.0 
```

**Comment by zhudock** [comment]
Same issue using Atom 1.14.1 x64

**Comment by zhudock** [comment]
Confirmed the Enable\Disable discussed in #115 seems to resolve the issue.
