### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sheet' of null

### ISSUE THREAD

**Issue by koltejas** [jccguimaraes/atom-project-viewer#12]
Steps that lead to the exception

1. Created a Group
2. Added one project to it.
3. From context menu  did "Edit group"
4. changed icon, color and pressed Edit group which gave the below error after which group vanished from panel

**Atom Version**: 1.2.4
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.2.20

### Stack Trace

Uncaught TypeError: Cannot read property 'sheet' of null

```
At C:\Users\Tejas\.atom\packages\project-viewer\lib\views\group-view.js:76

TypeError: Cannot read property 'sheet' of null
    at group-view.setName (C:\Users\Tejas\.atom\packages\project-viewer\lib\views\group-view.js:76:150)
    at group-view.setProjects (C:\Users\Tejas\.atom\packages\project-viewer\lib\views\group-view.js:35:14)
    at groups-view.addGroupNode (C:\Users\Tejas\.atom\packages\project-viewer\lib\views\groups-view.js:63:23)
    at groups-view.editGroupNode (C:\Users\Tejas\.atom\packages\project-viewer\lib\views\groups-view.js:23:40)
    at groups-view.updatedData (C:\Users\Tejas\.atom\packages\project-viewer\lib\views\groups-view.js:175:41)
    at Emitter.module.exports.Emitter.emit (C:\Users\Tejas\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at edit-group-view.editGroup (C:\Users\Tejas\.atom\packages\project-viewer\lib\views\edit-group-view.js:142:31)
    at HTMLButtonElement.addButtonClick (C:\Users\Tejas\.atom\packages\project-viewer\lib\views\edit-group-view.js:48:36)
```

### Commands

```
     -3:26.4.0 project-viewer:add-group (ul.list-tree.has-collapsable-children)
     -3:15.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:59.3.0 project-viewer:add-project (span.list-item)
     -2:14.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:26.4.0 tabs:close-all-tabs (li.tab.sortable.active.right-clicked)
     -1:01.7.0 project-viewer:edit-group (span.icon.icon-none)
```

### Config

```json
{
  "core": {},
  "project-viewer": {
    "startUp": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
fonts, v1.0.0
minimap, v4.16.1
php-cs-fixer, v2.5.1
pigments, v0.19.0
project-manager, v2.6.5
project-viewer, v0.2.20
sass-autocompile, v0.11.0

# Dev
No dev packages
```

**Comment by koltejas** [comment]
i also had similar error first time i created the group. After reloading atom however the group was there.

**Comment by jccguimaraes** [comment]
Hi,
Sorry for the late reply.
Thanks for reporting this. Will try to fix as soon as possible.
Need to check if it's related to windows or generally.

**Comment by jccguimaraes** [comment]
@koltejas Can you please confirm that this problem no longer occurs?
Thanks!

**Comment by bwbb** [comment]
Hi,

I'm afraid I still get the same issue on Windows, after updating with your fix:
```
Uncaught TypeError: Cannot read property 'classList' of undefined
C:\Users\<user>\.atom\packages\project-viewer\lib\views\groups-view.js:165
Hide Stack Trace
TypeError: Cannot read property 'classList' of undefined
    at groups-view.updatedData (C:\Users\<user>\.atom\packages\project-viewer\lib\views\groups-view.js:165:68)
    at Emitter.module.exports.Emitter.emit (C:\Users\<user>\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at add-group-view.constructGroup (C:\Users\<user>\.atom\packages\project-viewer\lib\views\add-group-view.js:94:31)
    at HTMLButtonElement.addButtonClick (C:\Users\<user>\.atom\packages\project-viewer\lib\views\add-group-view.js:30:36)
```

**Comment by jccguimaraes** [comment]
Thanks @bwbb.
I need to test in a win machine so I can sort this issues.
Although this is probably another issue. Will publish a little patch to try to fix for now without really testing on a win.

**Comment by jas99** [comment]
@jccguimaraes I also got this issue

**Comment by jccguimaraes** [comment]
still happening. yes

**Comment by jccguimaraes** [comment]
this seems to be a win problem. have resolved the error not breaking but i think it will not change colors. Can you please validate this? @jas99, @koltejas and @bwbb. thanks

**Comment by jas99** [comment]
@jccguimaraes 
Hi thr
Yeah it doesn't happen when you don't set the color and thus I don't.
Thx
Jas

**Comment by jccguimaraes** [comment]
yeah, will probably disable temporary for win users. :( that's a shame though.

**Comment by koltejas** [comment]
it only occurred after install, (no groups or projects). i haven't faced this error after that.
project viewer is working fine.

**Comment by koltejas** [comment]
Just for trial, i uninstalled project viewer and deleted the config json. and reinstalled. Had no error whatsoever :). Your latest version does not have this bug.

**Comment by jccguimaraes** [comment]
cool @koltejas. can you confirm that you cannot change the color of a group/project? i assume you are on a win right? thks

**Comment by koltejas** [comment]
yeah, group color is not changing.. changed color is saved in config file but does not reflect in the panel

**Comment by jccguimaraes** [comment]
found a work-a-round maybe this weekend will publish it
