### ISSUE TITLE
Uncaught TypeError: context.model.clearPaths is not a function

### ISSUE THREAD

**Issue by girlandhercode** [jccguimaraes/atom-project-viewer#121]
[Enter steps to reproduce:]

1. Right click on a folder in tree view
2. Select "Elevate to project..."
3. Fill out the PV Editor for the project
4. Hit "CREATE"

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.5

### Stack Trace

Uncaught TypeError: context.model.clearPaths is not a function

```
At C:\Users\cnmill05\.atom\packages\project-viewer\src\editor-view.js:676

TypeError: context.model.clearPaths is not a function
    at /packages/project-viewer/src/editor-view.js:676:19)
    at /packages/project-viewer/src/editor-view.js:714:17)
```

### Commands

```
  6x -6:52.2.0 core:backspace (input.hidden-input)
     -6:46.9.0 core:move-down (input.hidden-input)
     -6:45.8.0 core:confirm (input.hidden-input)
     -6:45.8.0 project-viewer:focusPanel (project-viewer.pv-has-icons)
     -6:44.3.0 core:move-down (div.package-detail.panels-item)
  2x -6:43.5.0 core:move-up (div.package-detail.panels-item)
     -6:42.1.0 command-palette:toggle (div.package-detail.panels-item)
 15x -6:15.8.0 core:move-down (input.hidden-input)
  3x -5:58 core:move-up (input.hidden-input)
     -5:52.5.0 core:confirm (input.hidden-input)
     -5:52.5.0 project-viewer:toggleSelectList (div.package-detail.panels-item)
     -5:51.5.0 core:move-down (input.hidden-input)
     -5:50.9.0 core:confirm (input.hidden-input)
     -5:50.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-vivid-syntax.theme-atom-material-ui.has-custom-icons)
  2x -2:13.6.0 project-viewer:togglePanel (input.hidden-input)
     -1:34.5.0 project-viewer:elevate-project (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
activate-power-mode-delete 0.6.1 
advanced-open-file 0.16.5 
ask-stack 2.2.0 
atom-beautify 0.29.17 
atom-clock 0.1.3 
atom-jinja2 0.6.0 
atom-material-ui 1.3.9 
atom-monokai 0.10.8 
atom-panda-syntax 0.18.0 
AtomicFreckle 0.2.0 
autocomplete-paths 1.0.5 
autoupdate-packages 1.3.1 
browser-plus 0.0.87 
captain-sweetheart 1.0.0 
climate-syntax 5.0.0 
color-picker 2.2.5 
colorio 0.1.0 
dark-side-of-the-moon-syntax 0.6.8 
dash 1.7.0 
Delete-Whitelines 0.6.3 
dracula-theme 2.0.0 
duotone-darkpool-syntax 1.1.0 
duotone-darksky 1.1.5 
electron-highlighter-syntax 1.7.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
expose 0.13.0 
file-icons 2.0.15 
file-types 0.5.5 
fold-comments 0.6.0 
git-plus 7.2.2 
github-atom-dark-syntax 0.3.2 
glowing-cursor 0.1.2 
highlight-line 0.12.0 
highlight-selected 0.12.0 
ice-world 0.0.0 
imdone-atom 2.1.18 
indent-guide-improved 1.4.12 
kachun 0.0.0 
keybinding-cheatsheet 0.1.1 
language-ansible 0.2.1 
language-docker 1.1.7 
language-generic-config 1.3.0 
language-gfm-enhanced 0.88.5 
language-ignore 1.5.2 
language-ini 1.17.0 
language-jade 0.7.2 
language-markdown 0.19.1 
linter 1.11.23 
linter-docker 0.1.4 
linter-js-yaml 1.2.6 
linter-jshint 3.0.2 
lollypop-unicorn 0.0.0 
markdown-preview-enhanced 0.9.8 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
nebula-syntax 0.4.3 
nebula-ui 0.5.3 
new-era-syntax 1.1.0 
one-outlander-ui 0.3.1 
open-recent 5.0.0 
outlander-syntax 2.0.0 
package-cop 0.2.10 
pigments 0.39.0 
pinned-tabs 0.4.2 
popfizz 0.0.0 
print-atom 0.1.1 
project-manager 3.3.3 
project-viewer 1.0.5 
proton 4.0.2 
proton-kai 0.1.0 
pure-syntax 0.2.1 
quark 0.1.4 
run-time-ui 13.39.0 
section-comment-snippets 2.4.1 
seti-syntax 1.0.1 
seti-ui 1.6.1 
snippet-generator 0.3.2 
spacegray-eighties-ui 1.2.0 
steam-pirate-ui 0.6.1 
sync-settings 0.8.1 
tabasco 0.5.0 
tinacious-design-syntax 1.0.0 
tomorrow 1.0.0 
vector-syntax 0.3.0 
vivid-syntax 2.1.0 
wakatime 6.0.13 
Wild-Cherry 0.9.0 
```

**Comment by jccguimaraes** [comment]
i am adding you to the contributors list

**Comment by jccguimaraes** [comment]
adding you as well @colorful-tones. @girlandhercode do you all mind me adding you?

**Comment by jccguimaraes** [comment]
a fix will be on next patch release

**Comment by tarikkavaz** [comment]
hi all is there a fix for this?

```
Uncaught TypeError: context.model.clearPaths is not a function
/Users/tarik/.atom/packages/project-viewer/src/editor-view.js:856
Hide Stack Trace
TypeError: context.model.clearPaths is not a function
    at HTMLElement._updateModel (/Users/tarik/.atom/packages/project-viewer/src/editor-view.js:856:19)
    at HTMLElement._clickSuccessButton (/Users/tarik/.atom/packages/project-viewer/src/editor-view.js:894:17)
The error was thrown from the project-viewer package. This issue has already been reported.
View Issue
```

**Comment by GreenGremlin** [comment]
I'm now encountering this bug as well. Was the fix for this somehow rolled back?

I'm on project-viewer 1.2.4. 

```
TypeError: context.model.clearPaths is not a function
    at HTMLElement._updateModel (/Users/jonathan/.atom/packages/project-viewer/src/editor-view.js:856:19)
    at HTMLElement._clickSuccessButton (/Users/jonathan/.atom/packages/project-viewer/src/editor-view.js:894:17)
```

**Comment by GreenGremlin** [comment]
It looks like the new project is actually created

**Comment by tarikkavaz** [comment]
I can add a project directly from the editor with no problem (⌃⌥⇧N)
this happens when I right click on the side/projectbar and try to add a project.

**Comment by tnqsoft** [comment]
Same error with me: 
TypeError: context.model.clearPaths is not a function
    at project-viewer-editor._updateModel (/home/nntuan/.atom/packages/project-viewer/src/editor-view.js:856:19)
    at project-viewer-editor._clickSuccessButton (/home/nntuan/.atom/packages/project-viewer/src/editor-view.js:894:17)

**Comment by ethernal** [comment]
This also happens when I have a project open (I always have one, there is no way to actually close it I think). 

The data for new project is filled based on old one or I am editing the old project instead of creating a new one and when I select "Create" the error shows up.

Hope to see this resolved. I'll try to manually edit the file to create a project but that's...

**Comment by jccguimaraes** [comment]
i will as we as rollback last PR

**Comment by jccguimaraes** [comment]
Please validate if this is fixed (reverted)

**Comment by ethernal** [comment]
It works. Tested just now. I see that the context menu behavior changed as well, allows to create project when hovering over the group but not to other project. Was that a bug? This is somewhat an UX issue.

**Comment by jccguimaraes** [comment]
Hey @ethernal, sorry for so late reply. I think that this got lost in recent changes. I believe that it was possible to create a project when clicked the context menu over another project, being able to only create a project whiten the group. But I will not prioritize this for now. But thanks for noticing this
