### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by siteleas** [jccguimaraes/atom-project-viewer#125]
[Enter steps to reproduce:]

1. Right click a project and click edit
2. Changed the colour and clicked update and then the error was fired

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Linux Mint
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.7
**User**: root

### Stack Trace

Uncaught TypeError: Cannot read property 'getAttribute' of undefined

```
At /root/.atom/packages/project-viewer/src/editor-view.js:26

TypeError: Cannot read property 'getAttribute' of undefined
    at /packages/project-viewer/src/editor-view.js:26:39)
    at /packages/project-viewer/src/editor-view.js:707:24)
```

### Commands

```
     -2:36.1.0 project-viewer:migrate03x (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:21.4.0 project-viewer:createGroupOrProject (ul.background-message.centered)
     -0:29.6.0 project-viewer:openEditor (div.list-item)
```

### Non-Core Packages

```
atom-lorempixel 0.1.0 
context-git 0.15.0 
emmet 2.4.3 
git-diff-details 1.4.0 
git-status 0.3.4 
git-time-machine 1.5.6 
lorem-insults 0.1.0 
markdown-preview-plus 2.4.2 
markdown-scroll-sync 2.1.2 
project-viewer 1.0.7 
Remote-FTP 0.10.5 
simple-drag-drop-text 0.3.4 
sync-settings 0.8.1 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.3.0 
```

**Comment by jccguimaraes** [comment]
messed up here. wait for next release please

**Comment by jccguimaraes** [comment]
@siteleas, can you please validate again? thanks
