### ISSUE TITLE
Uncaught ReferenceError: his is not defined

### ISSUE THREAD

**Issue by 4rkiel** [jccguimaraes/atom-project-viewer#13]
[Enter steps to reproduce below:]

1. load plugin

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.2.22

### Stack Trace

Uncaught ReferenceError: his is not defined

```
At /adhome/n/ni/niezgoda/.atom/packages/project-viewer/lib/views/groups-view.js:165

ReferenceError: his is not defined
    at groups-view.updatedData (/adhome/n/ni/niezgoda/.atom/packages/project-viewer/lib/views/groups-view.js:165:102)
    at Emitter.module.exports.Emitter.emit (/adhome/n/ni/niezgoda/.local/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at HTMLDivElement.groupClick (/adhome/n/ni/niezgoda/.atom/packages/project-viewer/lib/views/group-view.js:57:35)
```

### Commands

```
     -9:04.2.0 project-manager:list-projects (atom-text-editor.editor.mini.is-focused)
     -5:20.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:44.9.0 project-viewer:toggle (atom-text-editor.editor.mini.is-focused)
     -4:41.8.0 project-viewer:add-group (li.)
  3x -4:33.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:18.7.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -4:03.7.0 project-viewer:remove-group (span.list-item)
     -3:54.4.0 project-viewer:add-group (li.)
     -3:48.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:44.6.0 project-viewer:add-project (div.list-item)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "openEmptyEditorOnStart": false,
    "disabledPackages": [
      "about",
      "archive-view",
      "autosave",
      "bookmarks",
      "background-tips",
      "command-palette",
      "dev-live-reload",
      "exception-reporting",
      "language-java",
      "language-mustache",
      "language-perl",
      "metrics",
      "release-notes",
      "welcome"
    ],
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
project-viewer, v0.2.22

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
sorry @4rkiel 
that was a typo! fixed.

**Comment by jccguimaraes** [comment]
i really need to pace the refactor so i don't fall on this stupid errors :hammer:
