### ISSUE TITLE
ISSUE: Error on opening project

### ISSUE THREAD

**Issue by dexif** [jccguimaraes/atom-project-viewer#134]
Steps to reproduce:

1. Just open any project

**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.10

### Stack Trace

Uncaught TypeError: Cannot read property 'packageStates' of undefined

```
At /home/dexif/.atom/packages/project-viewer/src/project-view.js:261

TypeError: Cannot read property 'packageStates' of undefined
    at /packages/project-viewer/src/project-view.js:261:37)
    at /packages/project-viewer/src/project-view.js:15:8)
```

### Commands

```
     -5:00.1.0 command-palette:toggle (project-viewer.pv-has-icons)
  2x -4:57.8.0 core:backspace (input.hidden-input)
     -4:53.3.0 core:move-down (input.hidden-input)
     -4:53.1.0 core:confirm (input.hidden-input)
     -4:53.1.0 settings-view:view-installed-packages (project-viewer.pv-has-icons)
     -3:51.6.0 command-palette:toggle (div.package-detail.panels-item)
  8x -3:44 core:move-down (input.hidden-input)
  3x -3:37.1.0 core:move-up (input.hidden-input)
 16x -3:35.8.0 core:move-down (input.hidden-input)
     -3:28.6.0 core:confirm (input.hidden-input)
     -3:28.6.0 project-viewer:migrate03x (div.package-detail.panels-item)
     -3:15.8.0 project-viewer:createGroupOrProject (div.body-content)
     -1:38.5.0 project-viewer:openEditor (li.list-item.no-paths)
```

### Non-Core Packages

```
api-workbench 0.8.43 
atom-beautify 0.29.17 
atom-format-lua 0.1.5 
atom-formatter-jsbeautify 1.1.2 
atom-html-preview 0.1.22 
atom-less 0.1.10 
build-tools 4.5.7 
busy-signal 1.3.0 
context-git 0.15.5 
dash 1.7.1 
dash-on-cursor 0.1.0 
editor-stats 0.17.0 
git-blame 0.4.12 
git-commit 1.5.3 
git-control 0.8.2 
git-plus 7.3.3 
git-projects 1.17.0 
git-status 0.3.4 
git-time-machine 1.5.6 
goto-definition 1.2.1 
highlight-selected 0.12.0 
intentions 1.1.2 
jsformat 0.9.3 
language-babel 2.56.2 
language-lua 0.9.11 
language-nginx 0.6.2 
language-stylus 0.2.0 
language-svg 0.9.2 
language-vue 0.21.2 
linter 2.1.0 
linter-ui-default 1.2.1 
minimap 4.26.8 
minimap-autohide 0.10.1 
minimap-highlight-selected 4.5.0 
npm-plus 0.4.0 
package-cop 0.2.10 
package-sync-plus 0.1.2 
pigments 0.39.1 
pinned-tabs 0.4.2 
project-manager 3.3.3 
project-sidebar 1.3.0 
project-viewer 1.0.10 
refactor 0.11.3 
remote-edit 1.9.0 
scroll-searcher 5.2.0 
seti-icons 1.4.3 
sort-lines 0.14.0 
split-diff 1.2.1 
svg-preview 0.11.0 
svgo 2.8.1 
sync-settings 0.8.1 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.7.2 
webbox-color 0.5.9 
```

**Comment by PixelT** [comment]
I just wanna add this same bug ;)
👍

**Comment by jccguimaraes** [comment]
and you also on beta channel?

**Comment by jccguimaraes** [comment]
@dexif and @PixelT please check this out now

**Comment by dexif** [comment]
**Atom**: 1.16.0-beta0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.11


### Stack Trace

Uncaught TypeError: Cannot read property 'tree-view' of undefined

```
At /home/dexif/.atom/packages/project-viewer/src/project-view.js:253

TypeError: Cannot read property 'tree-view' of undefined
    at /packages/project-viewer/src/project-view.js:253:70)
    at /packages/project-viewer/src/project-view.js:15:8)
```

**Comment by jccguimaraes** [comment]
hope `1.0.12` solves this

**Comment by dexif** [comment]
Yes, it works ;)
