### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clients' of undefined

### ISSUE THREAD

**Issue by phillipbroberts** [jccguimaraes/atom-project-viewer#138]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.12

### Stack Trace

Uncaught TypeError: Cannot read property 'clients' of undefined

```
At C:\Users\phil\.atom\packages\project-viewer\src\database.js:366

TypeError: Cannot read property 'clients' of undefined
    at /packages/project-viewer/src/database.js:366:11)
    at /packages/project-viewer/src/main.js:472:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:10.3.0 project-viewer:migrate03x (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.6 
bitbucket-issues 0.1.1 
busy-signal 1.3.0 
docker 0.7.0 
git-checkout 0.3.2 
git-control 0.8.2 
intentions 1.1.2 
jenkins 0.3.5 
jira-issue-search 1.0.3 
jira-timesheet 0.2.0 
language-chef 0.9.0 
language-confluence-wiki 0.2.0 
language-groovy 0.6.0 
language-inspec 1.0.0 
language-terraform 0.8.0 
linter 2.1.2 
linter-chefstyle 1.0.0 
linter-docker 0.1.5 
linter-foodcritic 0.5.3 
linter-packer-validate 1.0.1 
linter-terraform-syntax 1.1.1 
linter-ui-default 1.2.1 
merge-conflicts 1.4.4 
open-on-bitbucket 0.4.0 
project-manager 3.3.4 
project-viewer 1.0.12 
ssh-config 0.10.1 
terraform-fmt 0.3.0 
```

**Comment by phillipbroberts** [comment]
This was actually a problem I was creating for myself. My bad.

**Comment by ArturoEduartes** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.0.12


### Stack Trace

Uncaught TypeError: Cannot read property 'clients' of undefined

```
At C:\Users\MyUser\.atom\packages\project-viewer\src\database.js:366

TypeError: Cannot read property 'clients' of undefined
    at /packages/project-viewer/src/database.js:366:11)
    at /packages/project-viewer/src/main.js:472:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:18.5.0 project-viewer:migrate03x (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-ctags 5.0.0 
language-blade 0.29.0 
laravel 0.7.1 
php-integrator-autocomplete-plus 1.3.0 
php-integrator-base 2.1.11 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
project-viewer 1.0.12 
```

![image](https://cloud.githubusercontent.com/assets/26888247/24736651/a5364e82-1a5f-11e7-9035-f5fc51800a42.png)

**Comment by jccguimaraes** [comment]
i have validated this as an actual bug, which is already fixed
this happens when you migrate from 0.3.x and actually you don't have any db for that version.

**Comment by jccguimaraes** [comment]
please validate
