### ISSUE TITLE
Uncaught TypeError: Cannot set property 'treeView' of undefined

### ISSUE THREAD

**Issue by lneveu** [jccguimaraes/atom-project-viewer#152]
Hi!

I've just updated Atom (1.17.0) and project-viewer, and I'm experiencing this issue 😢 

### How to reproduce?

1. Launch Atom
2. Try to open a projet using `project-viewer:toggleSelectList` command

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Windows 10
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.1.2

### Stack Trace

Uncaught TypeError: Cannot set property 'treeView' of undefined

```
TypeError: Cannot set property 'treeView' of undefined
    at /packages/project-viewer/src/project-view.js:270:26)
    at SelectListView.confirmed (/packages/project-viewer/src/select-list-view.js:52:8)
    at /packages/project-viewer/src/select-list-view.js:64:10)
    at /packages/project-viewer/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.0/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:08.8.0 project-viewer:toggleSelectList (div.panels-item)
     -0:07.5.0 core:confirm (input.hidden-input)
```

**Comment by lneveu** [comment]
Some updates:

When I disable the "Keep Context" option, all is working properly. After some investigations, I found that the storage file can't be load ([See here](https://github.com/jccguimaraes/atom-project-viewer/blob/master/src/project-view.js#L261-L270) : `serialization = atom.getStorageFolder().load(projectSHA);` -> return undefined) maybe because the `projectSHA` is wrong or the storage file does not exist.

**Comment by jccguimaraes** [comment]
cool, thanks, i will try to fix it
