### ISSUE TITLE
linter-ui-default package does not reload on switching projects

### ISSUE THREAD

**Issue by philip-hodder** [jccguimaraes/atom-project-viewer#154]
I actually raised this on the 'linter-ui-default' repo - but having seen the 'project-viewer' settings comment I thought I should raise this here.

Thanks!

[Enter steps to reproduce:]

1. Switch projects!

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.6.0

### Stack Trace

Failed to activate the linter-ui-default package

```
At Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Error (native)
    at StatusBarView.module.exports.StatusBarView.addRightTile (/Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:90:1)
    at /packages/linter-ui-default/lib/status-bar/index.js:91:67
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:625:1)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:150:1)
    at StatusBar.attach (/packages/linter-ui-default/lib/status-bar/index.js:87:40)
    at /packages/linter-ui-default/lib/index.js:55:26
    at Set.forEach (native)
    at Object.consumeStatusBar (/packages/linter-ui-default/lib/index.js:54:20)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:50:1)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:454:1)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:374:1
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:1
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:1)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:1)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:1)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:386:1)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:84:1)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:185:1)
    at list.forEach.pkg (/packages/project-viewer/src/packages.js:16:42)
    at Array.forEach (native)
    at /packages/project-viewer/src/packages.js:14:8)
    at /packages/project-viewer/src/project-view.js:303:22)
    at /packages/project-viewer/src/project-view.js:17:8)
```

### Commands

```
     -8:47.2.0 core:move-right (input.hidden-input)
  4x -8:44.6.0 core:backspace (input.hidden-input)
     -8:38 core:move-right (input.hidden-input)
     -8:36.8.0 core:move-left (input.hidden-input)
     -8:27.2.0 core:move-right (input.hidden-input)
  3x -8:19.8.0 core:backspace (input.hidden-input)
     -7:43.2.0 project-viewer:deleteGroupOrProject (li.list-item.no-paths)
     -7:25.7.0 core:copy (input.hidden-input)
     -7:07.6.0 project-viewer:openEditor (li.list-item)
  2x -6:34.2.0 editor:newline (input.hidden-input)
     -6:33.3.0 core:move-up (input.hidden-input)
     -6:32.3.0 core:paste (input.hidden-input)
     -5:49.1.0 editor:newline (input.hidden-input)
     -5:48.1.0 intentions:highlight (input.hidden-input)
     -5:36.1.0 core:move-right (input.hidden-input)
  2x -3:43.5.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
advanced-open-file 0.16.6 
api-docs 0.0.6 
ask-stack 2.2.0 
atom-html-preview 0.1.22 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-ungit 0.5.3 
atom-wrap-in-tag 0.6.0 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-date 0.4.0 
autocomplete-paths 1.0.5 
autocomplete-xml 0.9.4 
block-comment-plus 0.4.0 
build-tools 4.5.9 
build-tools-ant 0.1.1 
busy-signal 1.4.1 
character-table 0.4.3 
charcode-display 0.2.1 
color-picker 2.2.5 
css-specificity 0.2.2 
custom-title 1.0.1 
document-outline 1.5.0 
dumb-quoter 0.1.0 
expose 0.14.0 
file-icons 2.1.7 
filesize 3.0.0 
flex-tool-bar 0.12.0 
git-plus 7.9.2 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
imdone-atom 2.2.6 
import-sf-mono 1.0.1 
intentions 1.1.2 
isotope-ui 2.8.5 
keyboard-sounds 0.2.0 
language-diff 0.7.0 
language-jsoniq 1.8.0 
language-markdown 0.22.0 
language-pfm 0.82.0 
lines 0.13.1 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-htmlhint 1.3.3 
linter-js-standard 3.9.1 
linter-js-standard-engine 2.1.0 
linter-markdown 4.0.1 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.0 
markdown-preview-plus 2.4.9 
markdown-table-editor 0.5.2 
merge-conflicts 1.4.5 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-titles 1.11.0 
native-ui 0.20.6 
open-recent 5.0.0 
pdf-view 0.58.0 
pen-paper-coffee-syntax 0.14.9 
pigments 0.39.1 
pinned-tabs 1.1.0 
project-viewer 1.1.2 
random 1.3.0 
regex-railroad-diagram 0.17.0 
run-command2 1.12.2 
smart-quotes-plus 2.1.0 
split-diff 1.4.0 
standard-formatter 2.8.0 
Sublime-Style-Column-Selection 1.7.4 
svg-preview 0.11.0 
sync-settings 0.8.1 
tablr 1.8.3 
tag 0.5.0 
term3 0.22.1 
text-manipulation 0.6.0 
theme-reel 1.2.0 
theme-switcher 1.1.0 
tool-bar 1.1.0 
unity-dark-ui 2.0.9 
update-changelogs 0.1.0 
wordcount 2.10.4 
Zen 0.18.0 
```

**Comment by jccguimaraes** [comment]
hey @philip-hodder thanks for this issue, will have a look at that, for the moment just remove from the list please.

sorry about this

**Comment by jccguimaraes** [comment]
can't seem to reproduce this anymore.

Will close, but open if this is not accurate
