### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by jas99** [jccguimaraes/atom-project-viewer#16]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Enterprise N
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.2.24

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At C:\Users\jas\.atom\packages\project-viewer\lib\helpers\database.js:32

TypeError: Cannot read property 'toLowerCase' of undefined
  at sortData (C:\Users\jas\.atom\packages\project-viewer\lib\helpers\database.js:32:51)
  at Array.sort (native)
  at DataBase.updated (C:\Users\jas\.atom\packages\project-viewer\lib\helpers\database.js:31:42)
  at Emitter.module.exports.Emitter.emit (C:\Users\jas\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at add-project-view.constructProject (C:\Users\jas\.atom\packages\project-viewer\lib\views\add-project-view.js:83:31)
  at HTMLButtonElement.addButtonClick (C:\Users\jas\.atom\packages\project-viewer\lib\views\add-project-view.js:34:36)

```

### Commands

```
     -3:13.6.0 project-viewer:edit-group (span.list-item)
     -0:48 core:move-down (atom-text-editor.editor.is-focused)
  8x -0:47.3.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:45.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:43.8.0 core:move-down (atom-text-editor.editor.is-focused)
 21x -0:43.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:34.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:33.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:32.8.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:30.2.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:28.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.6.0 project-viewer:add-project (span.list-item)
  2x -0:11.1.0 core:select-right (atom-text-editor.editor.mini.is-focused)
     -0:10.1.0 core:select-left (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "line-ending-selector",
      "atom-terminal-panel",
      "project-manager",
      "atom-runner",
      "git-control",
      "project-view",
      "tool-bar-almighty",
      "seti-icons",
      "file-icon-supplement",
      "tool-bar-main",
      "nuclide-debugger-hhvm"
    ],
    "packagesWithKeymapsDisabled": [
      "activate-power-mode"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "project-viewer": {
    "startUp": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.6
atom-material-ui, v0.8.0
autocomplete-cmake, v0.3.1
autocomplete-modules, v1.3.1
custom-title, v1.0.1
dockerletion, v0.1.0
file-icons, v1.6.13
flex-tool-bar, v0.6.0
hyperclick, v0.0.35
icon-fonts, v1.10.0
keyboard-sounds, v0.2.0
language-batch, v0.3.3
language-cmake, v0.1.4
language-cpp14, v0.4.2
language-cuda, v0.1.0
language-docker, v1.1.6
line-ending-selector-unix, v0.0.9
linter, v1.11.3
linter-gcc, v0.5.5
linter-node-markdownlint, v0.2.2
markdown-preview-opener, v0.1.1
minimap, v4.17.0
node-debugger, v1.3.0
nuclide-buck-files, v0.0.35
nuclide-busy-signal, v0.0.35
nuclide-code-format, v0.0.35
nuclide-code-highlight, v0.0.35
project-viewer, v0.2.24
run-in-terminal, v0.5.0
sync-settings, v0.6.0
tool-bar, v0.1.9
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
thanks for pointing it out. Will try to replicate it and fix it.

**Comment by jccguimaraes** [comment]
can you please check if this continues to happen?

**Comment by jas99** [comment]
@jccguimaraes 
Hey thr
I think it might be something to do I was manually editing the json in response to issue I was having when setting color of the group. I don't have such issue anymore.

But I might suggest the json to be recreated if someone deletes it or empty out the file. That would help.

Thx 
Jas

**Comment by jccguimaraes** [comment]
cool feature! thx!
