### ISSUE TITLE
Uncaught TypeError: Cannot read property 'openOnWorkspace' of null

### ISSUE THREAD

**Issue by ShadowVariable** [jccguimaraes/atom-project-viewer#166]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'openOnWorkspace' of null

```
At /Users/leebanahmed/.atom/packages/project-viewer/src/projects-list.js:25

TypeError: Cannot read property 'openOnWorkspace' of null
    at ProjectsList.confirmSelection (/packages/project-viewer/src/projects-list.js:25:27)
    at Object.didConfirmSelection (/packages/project-viewer/src/projects-list-view.js:13:41)
    at SelectListView.confirmSelection (/packages/project-viewer/node_modules/atom-select-list/src/select-list-view.js:303:20)
    at SelectListView.didClickItem (/packages/project-viewer/node_modules/atom-select-list/src/select-list-view.js:218:10)
    at ListItemView.onclick (/packages/project-viewer/node_modules/atom-select-list/src/select-list-view.js:158:31)
    at ListItemView.didClick (/packages/project-viewer/node_modules/atom-select-list/src/select-list-view.js:351:10)
```

### Commands

```
     -0:05.0 project-viewer:toggleSelectList (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
angularjs 0.4.0 
atom-monokai 0.10.9 
atom-react-native-autocomplete 0.0.27 
atom-spotify2 2.1.2 
atom-typescript 10.1.14 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-ionic-framework 0.2.2 
autocomplete-js-import 1.4.0 
badass-react-snippets 1.1.0 
double-tag 0.4.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.0.15 
haskell-grammar 0.4.0 
highlight-bad-chars 1.0.5 
highlight-selected 0.12.0 
ionic-framework-snippets 1.2.1 
ionic-preview 0.7.0 
language-babel 2.57.7 
language-graphql 0.9.0 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 1.11.23 
linter-eslint 8.1.5 
linter-sass-lint 1.7.4 
merge-conflicts 1.4.4 
monokai-seti 0.7.0 
pigments 0.39.0 
prettier-atom 0.31.0 
project-viewer 1.2.0 
react-es6-snippets 0.3.0 
react-snippets 0.7.2 
refactorjs 1.0.0 
selector-to-tag 0.4.2 
set-syntax 0.3.2 
seti-icons 1.3.4 
seti-syntax 1.1.2 
seti-ui 1.9.0 
sort-lines 0.14.0 
split-diff 1.1.3 
toggler 0.3.0 
tool-bar 1.1.0 
```

**Comment by jccguimaraes** [comment]
hey @ShadowVariable, thanks for pointing this out. will try to have a look at that
