### ISSUE TITLE
Cannot add a new project: Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by maximkrusina** [jccguimaraes/atom-project-viewer#178]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.2.3

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/maxim/.atom/packages/project-viewer/src/main.js:637

ReferenceError: path is not defined
    at Object._createNewProject (/packages/project-viewer/src/main.js:637:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -0:24.5.0 project-viewer:createNewProject (div.body-content)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
busy-signal 1.4.3 
composer 0.5.0 
docker 0.8.0 
escape-utils 0.5.3 
intentions 1.1.5 
language-docker 1.1.8 
language-gettext 0.6.1 
language-mjml 1.10.0 
language-routeros-script 0.2.0 
language-textile 0.2.0 
linter 2.2.0 
linter-docker 0.2.1 
linter-js-yaml 1.2.8 
linter-mjml 1.2.0 
linter-ui-default 1.6.10 
mjml-preview 1.4.0 
multi-cursor 2.1.5 
php-integrator-refactoring 1.4.1 
platformio-ide-terminal 2.7.0 
project-viewer 1.2.3 
split-diff 1.5.1 
terminal-plus 0.14.5 
textile-preview 0.1.2 
```

**Comment by jccguimaraes** [comment]
hey sorry about that, please update the package

**Comment by maximkrusina** [comment]
Whoooow, it was kinda realtime :) Thanx a lot!!!

**Comment by jccguimaraes** [comment]
I was in the internet neighborhood :wink:
