### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (1...

### ISSUE THREAD

**Issue by camlafit** [jccguimaraes/atom-project-viewer#183]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Debian GNU/Linux
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.2.5

### Stack Trace

Uncaught IndexSizeError: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (1) is larger than the maximum index (0).

```
At /home/km/.atom/packages/project-viewer/src/colours.js:128

Error: Failed to execute 'deleteRule' on 'CSSStyleSheet': The index provided (1) is larger than the maximum index (0).
    at /packages/project-viewer/src/colours.js:128:30
    at Array.forEach (native)
    at /packages/project-viewer/src/colours.js:125:45)
    at /packages/project-viewer/src/colours.js:102:10)
    at Object._observeCustomHotZone (/packages/project-viewer/src/main.js:531:11)
    at /usr/share/atom/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:248:20)
    at SettingsPanel.set (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:237:27)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:315:24
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1694:26)
    at later (/usr/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -1:44.2.0 core:confirm (input.hidden-input)
     -1:01.7.0 github:toggle-git-tab (input#project-viewer.autoHide.input-checkbox)
     -0:48.1.0 core:delete (input.hidden-input)
     -0:42.8.0 core:backspace (input.hidden-input)
     -0:42.3.0 core:confirm (input.hidden-input)
  3x -0:40 core:backspace (input.hidden-input)
     -0:39.5.0 core:confirm (input.hidden-input)
  2x -0:08.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
adwaita-pro-ui 2.1.5 
atom-beautify 0.30.9 
atom-i18n 0.13.0 
atom-ide-ui 0.6.0 
auto-detect-indentation 1.3.0 
auto-encoding 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.2 
git-control 0.9.0 
html-entities 0.4.0 
hyperclick 0.0.0 
ide-php 0.7.3 
intentions 1.1.5 
language-smarty 1.8.0 
project-viewer 1.2.5 
sass-autocompile 0.13.3 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.4.0 
```

**Comment by jccguimaraes** [comment]
hey @camlafit, you are catching them all! :pokemon:

**Comment by camlafit** [comment]
Hello

:) sorry to find them

**Comment by wouter-willems** [comment]
Same problem for me! 
It happens when I have a pseudo selector that is not supported by a browser, causing my css to blow up
