### ISSUE TITLE
(issue): Failed to activate the status-bar package

### ISSUE THREAD

**Issue by EdwardSalter** [jccguimaraes/atom-project-viewer#184]
I have been getting the following error ever since I started using this great plugin a few months back and have decided that it is getting too annoying having to close an error popup every time I switch project.

Whilst the messages states that the error stems from the status-bar package, I thought it best to post here since it occurs after switching a project, I will duplicate to the status-bar package too if necessary.

[Enter steps to reproduce:]

1. Switch project.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package 1.8.14

### Stack Trace

Failed to activate the status-bar package

```
At validateDOMNesting.updatedAncestorInfo is not a function

TypeError: validateDOMNesting.updatedAncestorInfo is not a function
    at ReactDOMContainerInfo (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactDOMContainerInfo.js:25:58)
    at mountComponentIntoNode (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactMount.js:102:89)
    at ReactReconcileTransaction.perform (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at batchedMountComponentIntoNode (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactMount.js:124:21)
    at ReactDefaultBatchingStrategyTransaction.perform (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/Transaction.js:141:26)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:60:32)
    at Object.batchedUpdates (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactUpdates.js:95:33)
    at Object._renderNewRootComponent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactMount.js:317:24)
    at Object._renderSubtreeIntoContainer (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactMount.js:399:38)
    at Object.render (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/react-dom/lib/ReactMount.js:420:29)
    at GithubPackage.rerender (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/github/lib/github-package.js:336:30)
    at GithubPackage.consumeStatusBar (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/github/lib/github-package.js:383:16)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:256:22)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:690:42)
    at packagesToEnable.forEach.name (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:439:51)
    at Array.forEach (native)
    at disabledPackagesSubscription.config.onDidChange (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:439:30)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:693:26
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:884:35)
    at Config.module.exports.Config.setRawValue (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:670:25)
    at Config.module.exports.Config.set (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:248:20)
    at Config.module.exports.Config.removeAtKeyPath (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:407:18)
    at Package.module.exports.Package.enable (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:84:32)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:245:18)
    at list.forEach.pkg (/packages/project-viewer/src/packages.js:16:42)
    at Array.forEach (native)
    at /packages/project-viewer/src/packages.js:14:8)
    at /packages/project-viewer/src/project-view.js:329:24)
    at HTMLLIElement._onClickEvent (/packages/project-viewer/src/project-view.js:17:8)
```

### Commands

```
  2x -1:39.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
atom-formatter-jsbeautify 1.1.2 
atom-html-preview 0.2.5 
atom-import-js 0.12.0 
atom-jest-snippets 1.2.0 
atom-react-intl-snippets 1.0.2 
atom-wallaby 1.0.22 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
character-table 0.4.3 
close-tags 0.6.0 
color-picker 2.2.5 
docblockr 0.13.2 
dockerletion 0.2.0 
editor-stats 0.17.0 
editorconfig 2.2.2 
express-complete 0.2.0 
file-icons 2.1.14 
git-plus 7.10.0 
goto-last-edit 0.3.3 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-babel 2.80.3 
language-docker 1.1.8 
language-markdown 0.25.1 
language-powershell 4.0.0 
last-cursor-position 0.9.2 
lcov-info 0.12.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
markdown-folder 0.5.0 
markdown-toc 0.4.2 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
modern-react-snippets 0.3.0 
multi-cursor 2.1.5 
pigments 0.40.2 
prettier-atom 0.43.0 
project-viewer 1.2.5 
react-function-to-class 0.2.2 
regex-railroad-diagram 0.19.4 
sonarlint 1.0.2 
sort-lines 0.18.0 
source-preview 0.5.3 
sync-settings 0.8.3 
tester 1.4.0 
tester-jest 1.1.8 
todo-show 2.1.0 
toggle-quotes 1.0.1 
```

**Comment by jccguimaraes** [comment]
hi @EdwardSalter, sorry for this issue, it is a long time issue I know, and haven't found a suited solution. Please do 2 things to try to ease this. Go to the project-viewer settings and clear the entry where you list the packages (bottom) and replace the names of the packages with an empty string.

Then check if any of the linter, status-bar are disabled, and enabled them if you want.

Once again. This is a work in progress fix :(

**Comment by EdwardSalter** [comment]
@jccguimaraes, thanks for getting back to me.

I tried modifying the packages to reload as suggested by removing status-bar and leaving in linter and linter-ui.
No when switching projects the error does not occur thankfully and the status bar does seem to be working as expected for the new project.

I am happy with this workaround for now. Thank you very much :)

**Comment by jasmussen** [comment]
Hi folks, ❤️  atom project viewer.

I'm encountering the issue detailed in this ticket. Whenever I create a new project, then switch to it, the `status-bar` package gets deactivated and I have to manually activate it. 

This ticket is noted as "resolved", has a release been made? I'm on version 1.2.5.

**Comment by jccguimaraes** [comment]
Hi @jasmussen, it is more or less fixed... there is an issue with unsaved files that aren't being kept when switching between projects. Regarding the packages reloading, they need to be manually disabled as stated above for now.

I wan't to make the final fix for all of this.

Sorry for taking so long.

**Comment by jasmussen** [comment]
No worries, I'll be patient, thanks for working on this 👍
