### ISSUE TITLE
Failed to activate the project-viewer package

### ISSUE THREAD

**Issue by aolba** [jccguimaraes/atom-project-viewer#186]
[Enter steps to reproduce:]

1. uninstall previus version. and close atom
2. install it thru packages installer - > trow error after this

**Atom**: 1.23.0 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.2.5

### Stack Trace

Failed to activate the project-viewer package

```
At Cannot read property 'style' of undefined

TypeError: Cannot read property 'style' of undefined
    at HTMLElement.getPreferredWidth (/packages/project-viewer/src/main-view.js:455:37)
    at getPreferredSize (~/AppData/Local/atom/app-1.23.0/resources/app/src/dock.js:762:22)
    at Dock.getInitialSize (~/AppData/Local/atom/app-1.23.0/resources/app/src/dock.js:364:15)
    at Dock.handleDidAddPaneItem (~/AppData/Local/atom/app-1.23.0/resources/app/src/dock.js:240:39)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.addItem (~/AppData/Local/atom/app-1.23.0/resources/app/src/pane.js:630:24)
    at HTMLElement._buildPanel (/packages/project-viewer/src/main.js:390:13)
    at HTMLElement._addPanel (/packages/project-viewer/src/main.js:418:16)
    at Object._observePanelPosition (/packages/project-viewer/src/main.js:452:14)
    at Config.module.exports.Config.observeKeyPath (~/AppData/Local/atom/app-1.23.0/resources/app/src/config.js:674:13)
    at Config.module.exports.Config.observe (~/AppData/Local/atom/app-1.23.0/resources/app/src/config.js:155:27)
    at /packages/project-viewer/src/main.js:82:17)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:255:25)
    at ~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.23.0/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.23.0/resources/app/src/package-manager.js:695:42)
    at ~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.23.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.23.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.23.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.5 
block-and-line-comment 0.4.0 
busy-signal 1.4.3 
change-case 0.6.5 
color-picker 2.2.5 
file-icons 2.1.13 
goto-definition 1.3.4 
indent-guide-improved 1.4.13 
intentions 1.1.5 
json-schema 0.1.15 
language-babel 2.76.1 
language-javascript-jsx 0.3.7 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
omnisharp-atom 0.31.2 
project-viewer 1.2.5 
simple-panes 1.2.0 
```

**Comment by jccguimaraes** [comment]
hi @aolba, thanks, will investigate this

**Comment by kraeml** [comment]
[Enter steps to reproduce:]

1. Install and reinstall project-viewer
2. Allways same error.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.3.0


### Stack Trace

Failed to activate the project-viewer package

```
At watch /home/michl/.atom ENOSPC

Error: watch /home/michl/.atom ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at _directoryWatch (/packages/project-viewer/src/database.js:498:16)
    at /packages/project-viewer/src/database.js:446:3)
    at /packages/project-viewer/src/main.js:41:12)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:255:25)
    at /opt/atom/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at /opt/atom/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/opt/atom/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/opt/atom/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/opt/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:647:50)
    at /opt/atom/resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
ansible-snippets 0.2.0 
atom-beautify 0.30.9 
atom-ide-ui 0.9.1 
autocomplete-ansible 0.1.15 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.17 
go-plus 5.8.2 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
open-in-browser 0.5.2 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
project-viewer 1.3.0 
```
