### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attachChild' of null

### ISSUE THREAD

**Issue by darrencoutts118** [jccguimaraes/atom-project-viewer#187]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.2.5

### Stack Trace

Uncaught TypeError: Cannot read property 'attachChild' of null

```
At C:\Users\s04dc6\.atom\packages\project-viewer\src\editor-view.js:828

TypeError: Cannot read property 'attachChild' of null
    at _createModel (/packages/project-viewer/src/editor-view.js:828:13)
    at HTMLElement._clickSuccessButton (/packages/project-viewer/src/editor-view.js:902:19)
```

### Commands

```
     -5:15.4.0 tabs:close-all-tabs (div.title)
     -4:17.9.0 fuzzy-finder:toggle-file-finder (div.tool-panel.tree-view)
     -4:16.1.0 core:backspace (input.hidden-input)
  3x -4:14.1.0 core:move-down (input.hidden-input)
     -4:12.7.0 editor:consolidate-selections (input.hidden-input)
     -4:12.7.0 core:cancel (input.hidden-input)
     -4:12 command-palette:toggle (div.tool-panel.tree-view)
  8x -4:10.2.0 core:move-down (input.hidden-input)
  2x -4:08.8.0 core:move-up (input.hidden-input)
 10x -4:08.1.0 core:move-down (input.hidden-input)
     -4:04.0 core:confirm (input.hidden-input)
     -4:03.9.0 project-viewer:createNewProject (div.tool-panel.tree-view)
     -0:12.3.0 project-viewer:elevate-project (div.header.list-item.project-root-header)
```

### Non-Core Packages

```
atom-ide-ui 0.7.1 
atom-php-navigation 0.6.0 
busy-signal 1.4.3 
editorconfig 2.2.2 
highlight-selected 0.13.1 
hyperclick 0.0.0 
ide-php 0.7.4 
intentions 1.1.5 
language-vue 0.23.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-phpcs 1.6.8 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
php-integrator-navigation 1.2.1 
project-manager 3.3.5 
project-viewer 1.2.5 
remote-ftp 2.1.2 
tab-switcher 1.5.6 
```

**Comment by jccguimaraes** [comment]
hi @darrencoutts118, thanks for reporting this.
