### ISSUE TITLE
Failed to activate the project-viewer package

### ISSUE THREAD

**Issue by kraeml** [jccguimaraes/atom-project-viewer#192]
[Enter steps to reproduce:]

1. Install and reinstall project-viewer often
2. Allways same error.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package 1.3.0

### Stack Trace

Failed to activate the project-viewer package

```
At watch /home/michl/.atom ENOSPC

Error: watch /home/michl/.atom ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at _directoryWatch (/packages/project-viewer/src/database.js:498:16)
    at /packages/project-viewer/src/database.js:446:3)
    at /packages/project-viewer/src/main.js:41:12)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:255:25)
    at /opt/atom/resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at /opt/atom/resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/opt/atom/resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/opt/atom/resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/opt/atom/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/opt/atom/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:647:50)
    at /opt/atom/resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
ansible-snippets 0.2.0 
atom-beautify 0.30.9 
atom-ide-ui 0.9.1 
autocomplete-ansible 0.1.15 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.17 
go-plus 5.8.2 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
open-in-browser 0.5.2 
platformio-ide-terminal 2.8.0 
project-manager 3.3.5 
project-viewer 1.3.0 
```

**Comment by jccguimaraes** [comment]
hey @kraeml! please refer to #182 about this. Thank you 👍

**Comment by kraeml** [comment]
There is enough space on the divece. Projektviewer not running.
