### ISSUE TITLE
Uncaught TypeError: Cannot read property 'textContent' of undefined

### ISSUE THREAD

**Issue by FrankOcn** [jccguimaraes/atom-project-viewer#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Ubuntu 14.04.3
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.2.29

### Stack Trace

Uncaught TypeError: Cannot read property 'textContent' of undefined

```
At /home/frnkcn/.atom/packages/project-viewer/lib/views/add-project-view.js:68

TypeError: Cannot read property 'textContent' of undefined
    at add-project-view.constructProject (/home/frnkcn/.atom/packages/project-viewer/lib/views/add-project-view.js:68:67)
    at HTMLButtonElement.addButtonClick (/home/frnkcn/.atom/packages/project-viewer/lib/views/add-project-view.js:34:36)
```

### Commands

```
     -0:12.3.0 project-viewer:add-project (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "autocomplete-snippets",
      "autocomplete-atom-api",
      "metrics"
    ],
    "themes": [
      "atom-material-ui",
      "base16-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
autoclose-html, v0.19.0
base16-syntax, v1.6.2
color-picker, v2.0.14
fonts, v1.0.0
highlight-line, v0.11.0
minimap, v4.19.0
pigments, v0.19.5
project-viewer, v0.2.29

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
hi @FrankOcn.
Thanks for poiting this out. will make the necessary changes.

**Comment by jccguimaraes** [comment]
will make it available soon :night_with_stars:
