### ISSUE TITLE
Failed to load the project-viewer package

### ISSUE THREAD

**Issue by dsturm** [jccguimaraes/atom-project-viewer#45]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.0

### Stack Trace

Failed to load the project-viewer package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/danielsturm/.atom/packages/project-viewer/src/select-view.js:5:24)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/danielsturm/.atom/packages/project-viewer/src/index.js:10:21)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-sql",
      "php-class-tree",
      "php-integrator-base",
      "php-integrator-autocomplete-plus",
      "php-integrator-navigation",
      "php-integrator-tooltips",
      "remote-edit",
      "autoclose-html",
      "linter-stylelint",
      "activate-power-mode",
      "codekit-commands",
      "terminal-panel",
      "recent-projects",
      "atom-terminal-panel"
    ],
    "themes": [
      "one-dark-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.8.3
api-workbench, v0.8.30
atom-alignment, v0.12.1
atom-autocomplete-php, v0.18.9
atom-bootstrap4, v1.4.0
atom-material-syntax-dark, v0.2.5
auto-detect-indentation, v1.1.0
autocomplete-php, v0.3.7
autocomplete-wordpress-hooks, v0.2.0
cakephp-snippets, v0.6.1
cakephp3-snippets, v0.5.0
change-case, v0.6.0
color-picker, v2.1.1
css-comb, v2.4.3
docblockr, v0.7.3
documentation-renderer, v0.2.1
drunken-php, v0.2.1
editorconfig, v1.4.1
emmet, v2.4.3
emmet-snippets-compatibility, v1.0.6
file-icons, v1.7.13
git-diff-details, v1.3.0
git-hide, v0.1.2
git-time-machine, vundefined
git-wip, v0.2.2
javascript-snippets, v1.2.1
jquery-snippets, v11.0.0
language-hjson, v0.2.0
language-htaccess, v0.1.1
language-smarty, v1.7.0
language-sql-mysql, v0.3.1
laravel-snippets, v2.1.0
linter, v1.11.4
linter-php, v1.2.0
merge-conflicts, v1.4.4
minimap, v4.24.3
minimap-autohide, v0.10.1
minimap-git-diff, v4.3.1
minimap-highlight-selected, v4.4.0
php-cs-fixer, v2.5.6
pigments, v0.29.1
project-viewer, v0.3.0
react, v0.15.0
refactor, v0.6.0
sync-settings, v0.7.2
terminal-plus, v0.14.5
tree-view-git-branch, v0.1.2
tree-view-git-status, v0.2.3
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
really? :( don't know why it didn't install, it's one of the main packages in atom

**Comment by camlafit** [comment]
same problem on jessie version

**Comment by jccguimaraes** [comment]
let me check

**Comment by dsturm** [comment]
Thanks

**Comment by camlafit** [comment]
To complete debug information.

Module looks installed but can't be loaded. An atom start provide this error during module loading. 

**Atom Version**: 1.8.0
**System**: Debian GNU/Linux
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.0


### Stack Trace

Failed to load the project-viewer package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/km/.atom/packages/project-viewer/src/select-view.js:5:24)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/km/.atom/packages/project-viewer/src/index.js:10:21)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at /usr/share/atom/resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:457:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:397:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "styleguide",
      "package-generator",
      "markdown-preview",
      "open-on-github",
      "sass-autocompile"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/home/km/git",
    "themes": [
      "adwaita-pro-ui",
      "atom-dark-syntax"
    ]
  },
  "project-viewer": {
    "openBuffers": true
  }
}
```

### Installed Packages

```coffee
# User
adwaita-pro-ui, v2.1.4
auto-detect-indentation, v1.1.0
auto-encoding, v0.5.6
auto-indent, v0.5.0
color-picker, v2.1.1
linter, v1.11.4
linter-jshint, v2.1.0
linter-php, v1.2.0
linter-phpcs, v1.4.0
php-debug, v0.2.3
php-integrator-base, v0.9.3
php-integrator-navigation, v0.7.1
project-view, v0.5.0
project-viewer, v0.3.0

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
moved to `dependencies` instead of `devDependencies`. can you please check this?

**Comment by dsturm** [comment]
Looks good 👍

**Comment by camlafit** [comment]
ok here :)

**Comment by jccguimaraes** [comment]
please do `ctrl+alt+t`. i don't have issues, but seems to have one...

**Comment by jccguimaraes** [comment]
oh ok, it's an issue if you don't have projects :)

**Comment by camlafit** [comment]
ctrl+alt+t in my is shortkey to open terminal.
But crtr+alt+v no working more :/

**Comment by jccguimaraes** [comment]
is it being overriden? please use the `cmd+.` to open the keybinder resolver pleas

**Comment by camlafit** [comment]
Yes was overridden. Looks was to force project viewer shortcut, don't remenber.
Configuration restored :) 

Stay ctrl+alt+t, don't catch by atom as gnome took precedence. But look a local configuration and not generic.

**Comment by jccguimaraes** [comment]
ok, so to be clear
`ctrl+alt+t` opens the SelectView?
`ctrl+alt+v` toggles the Project-Viewer?

And if you all @dsturm and @camlafit feel happy, i can close this issue

**Comment by jccguimaraes** [comment]
forgot to publish the `0.3.2` version

**Comment by eduardomart** [comment]
Just had this issue updating to 0.3.25

**Comment by jccguimaraes** [comment]
wow! That is really strange! If you reload Atom, does it continue to happen?

**Comment by eduardomart** [comment]
No, it was only when I installed it.

**Comment by jccguimaraes** [comment]
i will look into it, see if i can recreate it. thanks
