### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by exitedprotek** [jccguimaraes/atom-project-viewer#48]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Windows 10 64bits
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At C:\Users\joels\.atom\packages\project-viewer\src\modal-update-component.js:122

TypeError: Cannot read property 'indexOf' of undefined
    at pv-update-modal.eachFolder (C:\Users\joels\.atom\packages\project-viewer\src\modal-update-component.js:122:45)
    at Array.forEach (native)
    at atom.pickFolder (C:\Users\joels\.atom\packages\project-viewer\src\modal-update-component.js:170:17)
    at EventEmitter.<anonymous> (C:\Users\joels\AppData\Local\atom\app-1.8.0\resources\app.asar\src\application-delegate.js:27:16)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -2:48.5.0 linter:lint (atom-text-editor.editor.is-focused)
     -2:45.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.seti-icons.seti-animate.theme-peacock-syntax.theme-one-dark-ui)
     -2:09.2.0 linter:lint (atom-text-editor.editor.is-focused)
     -2:00.4.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -1:29.9.0 project-viewer:toggle-display (input#project-viewer.autohide.)
     -1:22.8.0 project-viewer:create-client-item (ul.list-tree.has-collapsable-children.padded)
     -1:15.5.0 project-viewer:create-group-item (ul.list-tree.has-collapsable-children.padded)
     -1:06.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:06.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:50.8.0 project-viewer:create-client-item (ul.list-tree.has-collapsable-children.padded)
     -0:22.8.0 project-viewer:update-item (li#f53d2baa-781d-47b4-b896-945accab5083.list-nested-item.expanded)
```

### Config

```json
{
  "core": {
    "projectHome": "E:\\Lab\\Sites",
    "themes": [
      "one-dark-ui",
      "peacock-syntax"
    ]
  },
  "project-viewer": {
    "autohide": true,
    "statusBarVisibility": true
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.11.0
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.14
jquery-snippets, v11.0.0
language-blade, v0.25.3
linter, v1.11.8
merge-conflicts, v1.4.4
peacock-syntax, v1.4.0
pigments, v0.29.2
project-viewer, v0.3.2

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
Thanks for reporting this. Will investigate.

**Comment by jccguimaraes** [comment]
Please can you validate this issue again? Thanks

**Comment by exitedprotek** [comment]
It works perfectly!

Thanks! :)
