### ISSUE TITLE
Uncaught TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by luca85perez** [jccguimaraes/atom-project-viewer#6]
Error adding a new project.

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.2.8

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:190

TypeError: Arguments to path.join must be strings
  at f (path.js:190:13)
  at Object.filter (native)
  at Object.win32.join (path.js:195:38)
  at C:\Users\Desenvolvimento\.atom\packages\project-viewer\lib\views\project-view.js:29:86
  at Array.every (native)
  at project-view.setProject (C:\Users\Desenvolvimento\.atom\packages\project-viewer\lib\views\project-view.js:28:34)
  at groups-view.addProjectNode (C:\Users\Desenvolvimento\.atom\packages\project-viewer\lib\views\groups-view.js:80:25)
  at groups-view.updatedData (C:\Users\Desenvolvimento\.atom\packages\project-viewer\lib\views\groups-view.js:97:42)
  at Emitter.module.exports.Emitter.emit (C:\Users\Desenvolvimento\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at add-project-view.constructProject (C:\Users\Desenvolvimento\.atom\packages\project-viewer\lib\views\add-project-view.js:78:31)
  at HTMLButtonElement.addButtonClick (C:\Users\Desenvolvimento\.atom\packages\project-viewer\lib\views\add-project-view.js:34:36)

```

### Commands

```
 23x -8:53 core:backspace (input.hidden-input)
  2x -1:06.8.0 core:delete (input.hidden-input)
     -0:51.6.0 core:save (input.hidden-input)
     -0:49.3.0 core:close (input.hidden-input)
  2x -0:25.5.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-jade, v0.3.0
autocomplete-paths, v1.0.2
codeigniter, v0.2.0
docblockr, v0.7.3
emmet, v2.3.13
file-icons, v1.6.11
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
linter, v1.9.1
linter-jshint, v1.2.1
minimap, v4.15.0
minimap-autohide, v0.10.1
pigments, v0.18.1
project-viewer, v0.2.8
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
thanks for the input, will look at it. currently made some changes that bugged everything! :)
hang on please

**Comment by jccguimaraes** [comment]
please check if this continues to occur.

**Comment by luca85perez** [comment]
No, it's working fine. Thanks!

**Comment by jccguimaraes** [comment]
nice! :+1:
