### ISSUE TITLE
Uncaught TypeError: Cannot read property 'visible' of undefined

### ISSUE THREAD

**Issue by inssitu** [jccguimaraes/atom-project-viewer#68]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.14

### Stack Trace

Uncaught TypeError: Cannot read property 'visible' of undefined

```
At /Users/hello/.atom/packages/project-viewer/src/index.js:477

TypeError: Cannot read property 'visible' of undefined
    at Object.togglePanel (/Users/hello/.atom/packages/project-viewer/src/index.js:477:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
  7x -6:10.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:02.4.0 project-plus:toggle-project-finder (atom-text-editor.editor.is-focused)
  7x -6:01.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:57.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -5:04.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -5:02.0 project-plus:toggle-project-finder (atom-text-editor.editor.is-focused)
     -5:01.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:00.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  5x -4:58.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -4:54.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -4:53.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:44.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:43.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:24.2.0 project-viewer:create-item (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.panel-contrast.use-animations.compact-tree-view.theme-base16-tomorrow-dark-theme.theme-atom-material-ui.has-custom-icons)
     -3:08.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 project-viewer:toggle-display (div.panels)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "file-type-icons",
      "chrome-color-picker",
      "linter-tidy",
      "linter-sass-lint",
      "welcome",
      "project-plus"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-material-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-material-ui, v1.2.13
autoupdate-packages, v1.3.1
color-picker, v2.2.2
doge, v0.1.3
emmet, v2.4.3
file-icons, v1.7.16
language-vue, v0.14.0
linter, v1.11.14
linter-eslint, v7.2.4
meteor-api, v2.20.0
pigments, v0.31.1
project-viewer, v0.3.14
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
Thanks for opening an issue.
Will have a look at it.

*Are you interested in* **contributing** *to this project*? 💪

**Comment by DamnedScholar** [comment]
@inssitu, to clarify: this happens every time you try to toggle Project Viewer to be visible, even after reloading Atom?

**Comment by jccguimaraes** [comment]
will make the necessary safe check on this

**Comment by jccguimaraes** [comment]
Please validate if this still occurs.
Your **feedback** is vital! 👌
Thanks in advance.
