### ISSUE TITLE
v.0.3.19 - Switching between projects stalls

### ISSUE THREAD

**Issue by pete-hotchkiss** [jccguimaraes/atom-project-viewer#82]
# ISSUE: Switching between projects stalls
Description of the **issue**.

## Environment
- **OS**: OSX 10.11.2;
- **Atom**: 0.3.19;

## Steps
- switch 

Switching between projects throws alerts warning only _one instance of item [object Object] at Item Registry_ can exist.

Stack track is: 
```Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:387:25)
    at /Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:366:19
    at /Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:97:16
    at Function.module.exports.Emitter.simpleDispatch (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.didAddPane (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:306:27)
    at Pane.module.exports.Pane.setContainer (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:127:26)
    at PaneContainer.module.exports.PaneContainer.setRoot (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:164:17)
    at PaneContainer.module.exports.PaneContainer.deserialize (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:64:12)
    at Workspace.module.exports.Workspace.deserialize (/Users/petehotchkiss/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:175:33)
    at Object.workspaceDeserialization (/Users/petehotchkiss/.atom/packages/project-viewer/src/states.js:20:24)
    at pv-list-item.clickListener (/Users/petehotchkiss/.atom/packages/project-viewer/src/list-item-component.js:76:17)```

**Comment by pete-hotchkiss** [comment]
Here's the dialogue that pops up

![image](https://cloud.githubusercontent.com/assets/16895748/18028324/c42a4536-6c73-11e6-9ee5-99fcb0299e08.png)

**Comment by jccguimaraes** [comment]
Hi, thanks for reporting this.

Can you update the package to see if this wlstill works?

**Comment by jccguimaraes** [comment]
@pete-hotchkiss any update?

**Comment by jccguimaraes** [comment]
@pete-hotchkiss this is because i am targeting latest Atom version, you should update Atom first, please validate this.

Thanks

**Comment by jccguimaraes** [comment]
@pete-hotchkiss any update on this matter? thanks
