### ISSUE TITLE
tabs are broken when using project-viewer

### ISSUE THREAD

**Issue by vooor** [jccguimaraes/atom-project-viewer#9]
I like the approach you have on this project but there is a big problem when I use it with the tabs and file opened : 

When I open a file from the tree explorer or from a ctrl+t the file won't display. The file will actually be opened and I can switch to it via a ctrl+b but it won't show by itself. More than this the file won't appear in the tab bar, (the only thing I can have in the tab bar is actually the "settings" window).

I first thought that it was comming from the theme or another package but the behavior actually only and imediatly appear as soon as I activate atom-project-viewer and disapear only if I deactivate it and restart atom.

Have you any idea of the possible problem ?

**Comment by jccguimaraes** [comment]
Hi,

Am also experiencing some issues with the buffer files. :/

I am just finishing the edit projects and was counting on trying to fix
these issues.

Will sure take your feedback to help me understand what went wrong!

Thanks for the positive feedback.

Please add more feedback.

A ter, 10/11/2015, 16:47, vooor <notifications@github.com> escreveu:

**Comment by jccguimaraes** [comment]
hi @vooor,

can you please confirm if this issue still exists?
Have been opening files and switching between them just like you described and haven't found any problems so far.

Would appreciate that.
Thanks.

**Comment by vooor** [comment]
Hi,

I updated and restarted. it's better but sadly it's not completly fixed : when I open a file the buffer is opened and shown (which is a progress) but the tab bar is still empty of any file.

**Comment by vooor** [comment]
perhaps is that because of windows's paths ?

Here is an example of the kind of error I have :

```
Uncaught (in promise) SyntaxError: Invalid regular expression: /C:\dev\mhup\/: \ at end of pattern
    at new RegExp (native)
    at RegExp (native)
    at String.search (native)
    at C:\Users\benoit\.atom\packages\project-viewer\lib\helpers\database.js:87:33
    at Array.some (native)
    at DataBase.onDidAddPaneItem (C:\Users\benoit\.atom\packages\project-viewer\lib\helpers\database.js:86:55)
    at Emitter.module.exports.Emitter.emit (C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane-container.js:375:27)
    at C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane-container.js:359:28
    at Emitter.module.exports.Emitter.emit (C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.addItem (C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:340:20)
    at Pane.module.exports.Pane.activateItem (C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:311:14)
    at C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\workspace.js:492:18
    at process._tickCallback (node.js:368:9)(anonymous function) @ C:\Users\benoit\.atom\packages\project-viewer\lib\helpers\database.js:87onDidAddPaneItem @ C:\Users\benoit\.atom\packages\project-viewer\lib\helpers\database.js:86module.exports.Emitter.emit @ C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\event-kit\lib\emitter.…:86module.exports.PaneContainer.addedPaneItem @ C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane-container.js:375(anonymous function) @ C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane-container.js:359module.exports.Emitter.emit @ C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\event-kit\lib\emitter.…:86module.exports.Pane.addItem @ C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:340module.exports.Pane.activateItem @ C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\pane.js:311(anonymous function) @ C:\Users\benoit\AppData\Local\atom\app-1.2.0\resources\app.asar\src\workspace.js:492_tickCallback @ node.js:368
```

**Comment by vooor** [comment]
this path in lib/database.js at line 89 seem enough to fix it for me :
```javascript
return file.indexOf(projPath) !== -1;
```
instead of 
```javascript
return file.search(projPath) !== -1
```

**Comment by vooor** [comment]
I tryed to do a PR for you but you were faster than me. Thanks a lot :)

**Comment by jccguimaraes** [comment]
:) sorry about that ahahah.
Hope it fixes it! don't know why i used the search in the first place!
keep abusing it and report anything please
