### ISSUE TITLE
ISSUE: Project Swap on Atom Search

### ISSUE THREAD

**Issue by ackerdev** [jccguimaraes/atom-project-viewer#95]
I'm experiencing an odd issue when using the atom search palette that seems to be being caused by project-viewer. However, it doesn't appear to be consistent to reproduce.

When it is happening...
1. Open atom's search palette (cmd+f)
2. Type anything and hit enter
At this point, project-switcher kicks in and takes me to my alphabetically-first project, closing the search palette and not opening the search results tab.

If I go into my packages and disable atom-project-viewer, I can search again, though project-viewer throws errors when search is submitted. I've pasted the debug log below in case it might provide any useful information. Once I restart atom, and even if I then re-enable project-viewer, this bug will not appear immediately. I'm not sure what triggers this change in behavior.

I'm not 100% sure that project-viewer really is the culprit, but disabling it seems to temporarily fix the problem...

## Atom Debug Log

**Atom Version**: 1.12.3
**Electron Version**: 1.3.6
**System**: Mac OS X 10.12.1
**Thrown From**: [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) package, v0.3.27

### Stack Trace

Uncaught TypeError: Cannot read property 'dispatchEvent' of null

```
At /Users/nick/.atom/packages/project-viewer/src/select-view.js:65

TypeError: Cannot read property 'dispatchEvent' of null
    at PVSelectListView.confirmed (/Users/nick/.atom/packages/project-viewer/src/select-view.js:65:48)
    at PVSelectListView.confirmSelection (/Users/nick/.atom/packages/project-viewer/src/select-view.js:56:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:584:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:379:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:25.9.0 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:25.2.0 project-viewer:toggle-select-view (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.seti-animate.theme-solarized-dark-syntax.theme-seti-ui)
     -0:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:22.5.0 project-find:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-icons.seti-roboto.seti-animate.theme-solarized-dark-syntax.theme-seti-ui)
     -0:22.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:21.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:21.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:13.7.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:04.8.0 project-find:show (button.btn.icon.enablement.icon-playback-play)
     -0:04.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.1.0 project-find:show (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:01.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.3.0 project-find:show (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "atom-typescript",
      "project-viewer"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  },
  "project-viewer": {
    "autohide": true,
    "convertOldData": false,
    "hideHeader": true
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v10.1.11 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
language-typescript-grammars-only, v1.5.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-tslint, v0.11.1 (active)
project-viewer, v0.3.27 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (active)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by jccguimaraes** [comment]
Hi @ackerdev,
Thanks for this feedback, it indeed seems something is wrong with this package. I will have to make some experiments, sorry about it.

**Comment by jccguimaraes** [comment]
hi @ackerdev,
So regarding the errors in the console, i have fixed that, although that is really weird to show.

Please correct me if i am wrong.

You open the `find-and-replace` package with `cmd+f` and write something and press enter right?
I can only see a problem here, you previously have opened the `toggle Select view` from `project-viewer` from keypath `shift-ctrl-alt-v` and somehow, it keeps the focus on the `SelectListView` and when you press enter on the `find-and-replace` it magically triggers the first "selected" project.

**Comment by jccguimaraes** [comment]
indeed it is this issue! damn

**Comment by jccguimaraes** [comment]
@ackerdev please validade in the `0.3.28` version!

**Comment by ackerdev** [comment]
So far, no problems. If it didn't fix, I'll probably know by the end of today. I'll go ahead and close this assuming it's fixed, and if for some reason I experience it today I can always reopen.

Thanks for fixing this 😄
